### ISSUE TITLE
你好，我使用react-native run-ios报错

### ISSUE THREAD

**Issue by JserJser** [5ibinbin/react-native-nba#1]
博主，我对你的项目真的非常感兴趣，请问可以一起解答吗？
![image](https://user-images.githubusercontent.com/30041386/58243725-c755fd80-7d83-11e9-84bb-d768198f7584.png)

**Comment by nickyzhang-fe** [comment]
@JserJser 你可以参考一下这个链接   [https://github.com/facebook/react-native/issues/12737](url)  [https://stackoverflow.com/questions/37461703/print-entry-cfbundleidentifier-does-not-exist](url)
